# Application Configuration
spring.application.name=energy-user
server.port=8082

# RabbitMQ Configuration
spring.rabbitmq.host=192.168.159.146
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest

# User Configuration
energy.user.interval.min=1
energy.user.interval.max=5
energy.user.kwh.min=0.001
energy.user.kwh.max=0.01
energy.user.peak.morning.start=7
energy.user.peak.morning.end=10
energy.user.peak.evening.start=17
energy.user.peak.evening.end=22
